load("@trlc_sphinx_dependencies//:requirements.bzl", "requirement")

py_library(
    name = "trlc",
    srcs = ["trlc.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [requirement("sphinx")],
)
